spring.application.name=leetcodeclone

# Server Port
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:bitcodedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console (Access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console for debugging
spring.jpa.show-sql=true


# Judge0 API Configuration
judge0.api.url=https://judge0-ce.p.rapidapi.com/submissions
judge0.api.host=judge0-ce.p.rapidapi.com
judge0.api.key=ecb6726920msh3e0f5ce04d7216ap1e5cabjsnb84935b3b0e5